name: play_lab
description: A new Flutter project.
publish_to: 'none'

#Platform  Firebase App Id
#Android   1:478780527317:android:354bc924f271095fa3485c
#IOS       1:478780527317:ios:a4dd9a516223ecd9a3485c

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0
  readmore: ^2.1.0
  get: ^4.6.1
  http: ^1.2.1
  flutter_svg: ^2.0.4
  lottie: ^3.1.0
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.13
  flutter_rating_bar: ^4.0.0
  country_picker: ^2.0.20
  intl: ^0.18.0
  pin_code_fields: ^8.0.1
  flutter_widget_from_html: ^0.14.11
  flutter_inappwebview: ^6.0.0
  chewie: ^1.5.0
  video_player: ^2.6.1
  flutter_spinkit: ^5.1.0
  shimmer: ^3.0.0
  octo_image: ^2.0.0
  bottom_navy_bar: ^6.0.0
  path_provider: ^2.0.14
  flutter_staggered_animations: ^1.0.0
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^17.0.0
  firebase_analytics: ^10.2.1
  firebase_core: ^2.10.0
  awesome_dialog: ^3.0.2
  permission_handler: ^11.3.0
  firebase_auth: ^4.4.2
  url_launcher: ^6.1.10
  flutter_facebook_auth: ^6.1.1
  google_mobile_ads: ^4.0.0
  pay: ^2.0.0
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/
    - assets/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700


